version: '3.6'

services:
  fda_service_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fda_application_db
      MYSQL_HOST: localhost
      MYSQL_USER: fda_api_manager
      MYSQL_PASSWORD: password
    ports:
        - "3310:3306"

  fda_open_api_service:
    image: bernicdocker/open-fda-api
    ports:
      - 8040:8040
    depends_on:
      - fda_service_db
    environment:
      -spring.profiles.active: local-mysql
      -spring.datasource.url: jdbc:mysql://host.docker.internal:3310/fda_application_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

#Volumes
volumes:
  dbdata:
    driver: local
